name: feature_tests
version: 0.0.0

environment:
  sdk: 3.9.0-105.0.dev

dependencies:
  ffi: ^2.0.0
  code_assets: ^0.19.0
  hooks: ^0.19.0
  meta: ^1.12.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
