// generated by diplomat-tool
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

export class MyZst {
    constructor() {
        
    }


    method(foo) {
        const result = wasm.MyZst_method(foo);
    
        try {
            return result;
        }
        
        finally {}
    }
}